acmen:
  generatePath : /Users/gaowenfeng/project/data/
  codeGeneratorClass : com.acmen.acmenhelper.generate.DefaultCodeGenerator
  projectGeneratorClass : com.acmen.acmenhelper.generate.DefaultProjectGenerator
  dependencies:
    - tk.mybatis,mapper-spring-boot-starter,1.1.1
    - com.github.pagehelper,pagehelper,4.2.1
    - com.alibaba,fastjson,1.2.44





