acmen:
  project:
    generate_path : /Users/gaowenfeng/project/data/
    code_generator : defaultCodeGenerator
    project_generator : defaultProjectGenerator
  dependencies:
    - tk.mybatis,mapper-spring-boot-starter,1.1.1
    - com.github.pagehelper,pagehelper,4.2.1
    - com.alibaba,fastjson,1.2.44





