acmen:
  generatePath : /Users/gaowenfeng/project/data/
  codeGeneratorClass : com.acmen.acmenhelper.generate.defaults.DefaultCodeGenerator
  projectGeneratorClass : com.acmen.acmenhelper.generate.defaults.DefaultProjectGenerator
  dependencies:
    - tk.mybatis,mapper-spring-boot-starter,1.1.1
    - com.github.pagehelper,pagehelper,4.2.1
    - com.alibaba,fastjson,1.2.44
  spiltmodule:
    dependencies:
      - org.springframework.boot,spring-boot-starter-web
      - org.springframework.boot,spring-boot-starter-test
      - org.mybatis.spring.boot,mybatis-spring-boot-starter,1.3.2
      - mysql,mysql-connector-java,runtime
      - org.projectlombok,lombok,1.16.18
      - tk.mybatis,mapper-spring-boot-starter,1.1.1
      - com.github.pagehelper,pagehelper,4.2.1
      - com.alibaba,fastjson,1.2.44
server:
  port: 9090






